//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group2_iCLOTHINGApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatus
    {
        public int orderID { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> statusDate { get; set; }
        public int cartID { get; set; }
    
        public virtual ShoppingCart ShoppingCart { get; set; }
    }
}
