//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group2_iCLOTHINGApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPassword
    {
        public int userID { get; set; }
        public string userEncryptedPassword { get; set; }
        public Nullable<System.DateTime> passwordExpiryDate { get; set; }
        public Nullable<System.DateTime> userAccountExpiryDate { get; set; }
    
        public virtual UserAccessLevel UserAccessLevel { get; set; }
    }
}
